channels:
    - pytorch
    - conda-forge
    - defaults
name:
    antibodies-gpu-tf
dependencies:
    - cpuonly
    - imageio
    - h5py
    - napari
    - pip
    - pytorch
    - scikit-image
    - tensorflow-gpu 1.14
    - torchvision
    - tqdm
    - vigra
    - pip:
        - stardist
