channels:
    - pytorch
    - conda-forge
    - defaults
name:
    antibodies-gpu
dependencies:
    - configargparse
    - cudatoolkit=10.1
    - imageio
    - h5py
    - napari
    - pip
    - pytorch
    - scikit-image
    - torchvision
    - tqdm
    - vigra
    - pymongo
    - xlrd
    - pip:
        - tensorflow==1.15
        - stardist