channels:
    - pytorch
    - conda-forge
    - defaults
name:
    antibodies
dependencies:
    - configargparse
    - cpuonly
    - imageio
    - h5py
    - napari
    - pip
    - pytorch
    - scikit-image
    - tensorflow 1.15
    - torchvision
    - tqdm
    - vigra
    - pymongo
    - xlrd
    - slackclient
    - pip:
        - stardist
